/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package water_quality_monitoring_system;

import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class interface01 extends javax.swing.JFrame {

    /**
     * Creates new form interface01
     */
    public static String portsender="";//sseriel port changeer
    public static interface01 informationFrame1=new interface01(); 
    public interface01() {
        
        final String DEGREE  = "\u00b0";//degree charactor
        initComponents();
       // this.setIconImage(new ImageIcon(getClass().getResource("/Images/logo7.png")).getImage());
        this.setSize(710,500);
        temparatureCelcius.setText(DEGREE+"C");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        conductivityPanel = new javax.swing.JPanel();
        ConductivityLabel = new javax.swing.JLabel();
        conductivitySlider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        informationPanel = new javax.swing.JPanel();
        informationLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tempContainer = new javax.swing.JPanel();
        temparaturePanel = new javax.swing.JPanel();
        temparatureValueLabel = new javax.swing.JLabel();
        temparatureCelcius = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pHpanel = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        pHLabel = new javax.swing.JLabel();
        pHlevelLabel = new javax.swing.JLabel();
        logoPanel = new javax.swing.JPanel();
        logolabel = new javax.swing.JLabel();
        statisticPanel = new javax.swing.JPanel();
        statisticLabel = new javax.swing.JLabel();
        portChangerPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        portCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 100));
        setSize(new java.awt.Dimension(400, 100));

        backgroundPanel.setBackground(new java.awt.Color(220, 230, 240));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        conductivityPanel.setBackground(new java.awt.Color(220, 230, 240));
        conductivityPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ConductivityLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sliderimage5.png"))); // NOI18N
        ConductivityLabel.setText("conlbl");

        conductivitySlider.setBackground(new java.awt.Color(230, 230, 240));
        conductivitySlider.setMajorTickSpacing(10);
        conductivitySlider.setMinorTickSpacing(1);
        conductivitySlider.setPaintLabels(true);
        conductivitySlider.setPaintTicks(true);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel1.setText("Low Ion Density");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel2.setText("Normal Ion Density");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel3.setText("High Ion Density");

        jLabel5.setText("Conductivity Level");

        javax.swing.GroupLayout conductivityPanelLayout = new javax.swing.GroupLayout(conductivityPanel);
        conductivityPanel.setLayout(conductivityPanelLayout);
        conductivityPanelLayout.setHorizontalGroup(
            conductivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conductivityPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(conductivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conductivityPanelLayout.createSequentialGroup()
                        .addGroup(conductivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(conductivityPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel2)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel3))
                            .addComponent(conductivitySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConductivityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conductivityPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))))
        );
        conductivityPanelLayout.setVerticalGroup(
            conductivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conductivityPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConductivityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conductivitySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(conductivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        backgroundPanel.add(conductivityPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 510, 170));

        informationPanel.setBackground(new java.awt.Color(220, 240, 240));
        informationPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        informationPanel.setToolTipText("Status");
        informationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        informationLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        informationPanel.add(informationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 230, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Status");
        informationPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 50, -1));

        backgroundPanel.add(informationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 270, 130));

        tempContainer.setBackground(new java.awt.Color(255, 255, 255));
        tempContainer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tempContainer.setToolTipText("Temparature");
        tempContainer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tempContainerMouseEntered(evt);
            }
        });
        tempContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        temparaturePanel.setBackground(new java.awt.Color(255, 255, 255));

        temparatureValueLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        temparatureValueLabel.setText("23.45");
        temparaturePanel.add(temparatureValueLabel);

        temparatureCelcius.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        temparatureCelcius.setText("C");
        temparaturePanel.add(temparatureCelcius);

        tempContainer.add(temparaturePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, 90));

        jLabel4.setText("Temparature");
        tempContainer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 80, 20));

        backgroundPanel.add(tempContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 230, 130));

        pHpanel.setBackground(new java.awt.Color(200, 230, 240));
        pHpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pHpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSlider1.setBackground(new java.awt.Color(200, 230, 240));
        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(14);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        pHpanel.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 50, 270));

        pHLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pH_Scale.jpg"))); // NOI18N
        pHLabel.setText("jLabel6");
        pHpanel.add(pHLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 40, 270));

        pHlevelLabel.setText("pH Level");
        pHpanel.add(pHlevelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 20));

        backgroundPanel.add(pHpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 130, 310));

        logoPanel.setBackground(new java.awt.Color(220, 230, 240));
        logoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo7.png"))); // NOI18N
        logoPanel.add(logolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 90));

        backgroundPanel.add(logoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 90));

        statisticPanel.setBackground(new java.awt.Color(210, 210, 240));
        statisticPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        statisticPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statisticLabel.setBackground(new java.awt.Color(2, 240, 240));
        statisticLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/statimage.png"))); // NOI18N
        statisticLabel.setText("Statistics");
        statisticLabel.setToolTipText("Statistics");
        statisticPanel.add(statisticLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 90));

        backgroundPanel.add(statisticPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 130, 100));

        portChangerPanel.setBackground(new java.awt.Color(170, 200, 240));
        portChangerPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Serial Port :");
        portChangerPanel.add(jLabel6);

        portCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COM0", "COM1", "COM2", "COM3", "COM4", "COM5", "COM6" }));
        portCombo.setSelectedIndex(3);
        portCombo.setToolTipText("Serial Port");
        portCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portComboActionPerformed(evt);
            }
        });
        portChangerPanel.add(portCombo);

        backgroundPanel.add(portChangerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 170, 50));

        getContentPane().add(backgroundPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempContainerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempContainerMouseEntered
       
    }//GEN-LAST:event_tempContainerMouseEntered

    private void portComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portComboActionPerformed

    /**
     * @param args the command line arguments
     */
   
    
    
    
    public void cunductSlider(int condctValue){//seting value on the slider
    conductivitySlider.setValue(condctValue);
    
    }
    
    public void setInformationLabel(String massage){
    
    informationLabel.setText(massage);
    
    }
    
    public void setTemparatue(String temp){
    temparatureValueLabel.setText(temp);
    }
    
    public void comboBox(){
    
    int port=portCombo.getSelectedIndex();//geting value for the seriel port
    
    if(port==0){
        portsender="COM0";//assighing values to the seriel port
    }else if(port==1){
        portsender="COM1";
    }else if(port==2){
        portsender="COM2";
    }else if(port==3){
        portsender="COM3";
    }else if(port==4){
        portsender="COM4";
    }else if(port==5){
        portsender="COM5";
    }else if(port==6){
        portsender="COM6";
    }else if(port==7){
        portsender="COM7";
    }
    
    
    
    }
    
     public static String setPort(){
     
      
     return portsender;
     }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConductivityLabel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel conductivityPanel;
    private javax.swing.JSlider conductivitySlider;
    private javax.swing.JLabel informationLabel;
    private javax.swing.JPanel informationPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel logolabel;
    private javax.swing.JLabel pHLabel;
    private javax.swing.JLabel pHlevelLabel;
    private javax.swing.JPanel pHpanel;
    private javax.swing.JPanel portChangerPanel;
    private javax.swing.JComboBox<String> portCombo;
    private javax.swing.JLabel statisticLabel;
    private javax.swing.JPanel statisticPanel;
    private javax.swing.JPanel tempContainer;
    private javax.swing.JLabel temparatureCelcius;
    private javax.swing.JPanel temparaturePanel;
    private javax.swing.JLabel temparatureValueLabel;
    // End of variables declaration//GEN-END:variables
}
